name: Update Route 53 DNS

on:
  push:
    branches:
      - master

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Update package information
        run: sudo apt-get update

      - name: Install AWS CLI
        run: sudo apt-get install -y --fix-missing awscli
