name: Route 53 DNS

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Enter the domain name'
        required: true
      ip:
        description: 'Enter the IP address'
        required: true
  push:
    branches:
      - master

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set variables
        run: |
          DOMAIN_NAME="${{ github.event.inputs.domain }}"
          IP_ADDRESS="${{ github.event.inputs.ip }}"

      - name: Update package information
        run: sudo apt-get update

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region N.Virginia 

      - name: Update Route 53 DNS record
        run: |
          aws route53 change-resource-record-sets \
            --hosted-zone-id "${{ secrets.AWS_HOSTED_ZONE_ID }}" \
            --change-batch '{
              "Changes": [
                {
                  "Action": "UPSERT",
                  "ResourceRecordSet": {
                    "Name": "'"$DOMAIN_NAME"'",
                    "Type": "A",
                    "TTL": 300,
                    "ResourceRecords": [
                      {
                        "Value": "'"$IP_ADDRESS"'"
                      }
                    ]
                  }
                }
              ]
            }'
