name: Route 53 DNS

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Enter the domain name'
        required: true
      ip:
        description: 'Enter the IP address'
        required: true
  push:
    branches:
      - master

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set variables
        run: |
          DOMAIN_NAME="${{ github.event.inputs.domain }}"
          IP_ADDRESS="${{ github.event.inputs.ip }}"

      - name: Update package information
        run: sudo apt-get update

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli
