name: Deploy to Route 53

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain name to update'
        required: true
      ip_address:
        description: 'IP address to set for the A record'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-aws-region

      - name: Deploy to Route 53
        run: |
          # Extracting inputs
          domainName="${{ github.event.inputs.domain }}"
          ipAddress="${{ github.event.inputs.ip_address }}"

          # Replace these values with your actual values
          hostedZoneId="YOUR_HOSTED_ZONE_ID"

          # Update A record
          aws route53 change-resource-record-sets \
            --hosted-zone-id $hostedZoneId \
            --change-batch "{
              \"Changes\": [{
                \"Action\": \"UPSERT\",
                \"ResourceRecordSet\": {
                  \"Name\": \"$domainName\",
                  \"Type\": \"A\",
                  \"TTL\": 300,
                  \"ResourceRecords\": [{\"Value\": \"$ipAddress\"}]
                }
              }]
            }"

          echo "DNS records updated successfully"
