name: Update Route 53 DNS

on:
  push:
    branches:
      - master

jobs:
  update-dns:
    runs-on: ubuntu-latest

    env:
      DOMAIN_NAME: "practice.kubeace.com"  
      IP_ADDRESS: "123.456.789.012"  

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Update Route 53 DNS
        run: |
          # Set your AWS credentials and region
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}

          # Update Route 53 DNS record using specified domain and IP
          aws route53 change-resource-record-sets \
            --hosted-zone-id "${{ secrets.AWS_HOSTED_ZONE_ID }}" \
            --change-batch '{
              "Changes": [
                {
                  "Action": "UPSERT",
                  "ResourceRecordSet": {
                    "Name": "'"$DOMAIN_NAME"'",
                    "Type": "A",
                    "TTL": 300,
                    "ResourceRecords": [
                      {
                        "Value": "'"$IP_ADDRESS"'"
                      }
                    ]
                  }
                }
              ]
            }'
